name: Gallery Bot - Slack to GitHub

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-slack-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install slack-sdk pyyaml requests pillow pillow-heif
    
    - name: Process Slack messages (add and delete)
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      run: |
        python << 'EOF'
        import os
        import yaml
        import requests
        from slack_sdk import WebClient
        from slack_sdk.errors import SlackApiError
        from datetime import datetime, timedelta
        import re
        from PIL import Image
        import io
        
        # Try to import HEIF support
        try:
            from pillow_heif import register_heif_opener
            register_heif_opener()
        except ImportError:
            pass
        
        def optimize_to_webp(image_data, max_width=1920, quality=80):
            """
            Optimize image to WebP:
            - Resize to max width while maintaining aspect ratio
            - Convert to WebP format
            - Compress to specified quality
            """
            try:
                img = Image.open(io.BytesIO(image_data))
                
                # Convert RGBA/P to RGB for WebP
                if img.mode in ('RGBA', 'P', 'LA'):
                    background = Image.new('RGB', img.size, (255, 255, 255))
                    if img.mode == 'P':
                        img = img.convert('RGBA')
                    background.paste(img, mask=img.split()[-1] if img.mode in ('RGBA', 'LA') else None)
                    img = background
                elif img.mode != 'RGB':
                    img = img.convert('RGB')
                
                # Resize if needed
                if img.width > max_width:
                    ratio = max_width / img.width
                    new_height = int(img.height * ratio)
                    img = img.resize((max_width, new_height), Image.Resampling.LANCZOS)
                
                # Save as WebP
                output = io.BytesIO()
                img.save(output, format='WebP', quality=quality, method=6)  # method=6 = best compression
                output.seek(0)
                
                original_size = len(image_data)
                optimized_size = len(output.getvalue())
                reduction = ((original_size - optimized_size) / original_size) * 100
                
                return output.getvalue(), original_size, optimized_size, reduction
                
            except Exception as e:
                print(f"⚠️ Optimization failed: {str(e)}")
                return image_data, len(image_data), len(image_data), 0
        
        # Initialize Slack client
        client = WebClient(token=os.environ["SLACK_BOT_TOKEN"])
        channel_id = os.environ["SLACK_CHANNEL_ID"]
        
        # Get messages from last 2 hours
        two_hours_ago = (datetime.now() - timedelta(hours=2)).timestamp()
        
        changes_made = False
        additions = []
        deletions = []
        
        try:
            # Fetch recent messages
            result = client.conversations_history(
                channel=channel_id,
                oldest=str(two_hours_ago),
                limit=50
            )
            
            messages = result["messages"]
            new_entries = []
            entries_to_delete = []
            
            # Load existing YAML
            yaml_path = "_data/gallery/items.yml"
            with open(yaml_path, "r") as f:
                existing_entries = yaml.safe_load(f) or []
            
            # STEP 1: Check for deletions (messages with ❌ reaction)
            for message in messages:
                message_ts = message.get("ts", "")
                
                if "reactions" in message:
                    for reaction in message["reactions"]:
                        if reaction["name"] == "x":  # ❌ emoji
                            for entry in existing_entries:
                                if entry.get("slack_ts") == message_ts:
                                    entries_to_delete.append(entry)
                                    deletions.append(entry["description"])
                                    break
            
            # STEP 2: Check for new additions (no ❌ reaction)
            for message in messages:
                message_ts = message.get("ts", "")
                
                # Skip if message has ❌ reaction
                has_x_reaction = False
                if "reactions" in message:
                    for reaction in message["reactions"]:
                        if reaction["name"] == "x":
                            has_x_reaction = True
                            break
                
                if has_x_reaction:
                    continue
                
                # Check if message has files
                if "files" in message:
                    for file in message["files"]:
                        if file["mimetype"].startswith("image/"):
                            text = message.get("text", "").strip()
                            
                            if not text or message.get("bot_id"):
                                continue
                            
                            # Check if already exists (by slack_ts)
                            already_exists = any(e.get("slack_ts") == message_ts for e in existing_entries)
                            if already_exists:
                                continue
                            
                            # Parse format
                            parts = [p.strip() for p in text.split("|")]
                            description = parts[0] if len(parts) > 0 else "Untitled"
                            
                            year = None
                            month = None
                            place = None
                            
                            if len(parts) >= 2:
                                time_part = parts[1].strip()
                                if re.match(r'^\d{4}$', time_part):
                                    year = time_part
                                else:
                                    year_match = re.search(r'\b(19|20)\d{2}\b', time_part)
                                    if year_match:
                                        year = year_match.group()
                                        month_part = time_part.replace(year, '').strip()
                                        if month_part:
                                            month = month_part
                            
                            if len(parts) >= 3:
                                place = parts[2].strip()
                            
                            # Generate unique ID
                            unique_id = message_ts.replace(".", "_")
                            
                            # Generate filename (always .webp)
                            timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
                            clean_desc = re.sub(r'[^a-zA-Z0-9\s-]', '', description.lower())
                            clean_desc = re.sub(r'\s+', '-', clean_desc)[:50]
                            filename = f"{timestamp}-{clean_desc}.webp"
                            
                            # Download image
                            print(f"⬇️ Downloading: {file['name']}")
                            headers = {"Authorization": f"Bearer {os.environ['SLACK_BOT_TOKEN']}"}
                            download_url = file.get("url_private_download", file.get("url_private"))
                            img_response = requests.get(download_url, headers=headers)
                            
                            if img_response.status_code == 200:
                                # Optimize to WebP
                                print(f"🔧 Optimizing to WebP...")
                                optimized_data, orig_size, new_size, reduction = optimize_to_webp(img_response.content)
                                
                                print(f"   Original: {orig_size / 1024:.1f} KB")
                                print(f"   WebP: {new_size / 1024:.1f} KB")
                                print(f"   Reduction: {reduction:.1f}%")
                                
                                # Save
                                filepath = f"assets/gallery/{filename}"
                                with open(filepath, "wb") as f:
                                    f.write(optimized_data)
                                
                                print(f"✅ Saved: {filepath}")
                                
                                # Create YAML entry
                                entry = {
                                    "id": unique_id,
                                    "filename": filename,
                                    "description": description,
                                    "slack_ts": message_ts
                                }
                                
                                if year:
                                    entry["year"] = int(year)
                                if month:
                                    entry["month"] = month
                                if place:
                                    entry["place"] = place
                                
                                new_entries.append(entry)
                                additions.append(description)
                                changes_made = True
                            else:
                                print(f"❌ Failed to download: {img_response.status_code}")
            
            # STEP 3: Apply deletions
            if entries_to_delete:
                for entry in entries_to_delete:
                    filepath = f"assets/gallery/{entry['filename']}"
                    if os.path.exists(filepath):
                        os.remove(filepath)
                        print(f"🗑️ Deleted: {filepath}")
                    
                    existing_entries = [e for e in existing_entries if e.get("id") != entry.get("id")]
                
                changes_made = True
            
            # STEP 4: Add new entries
            if new_entries:
                existing_entries.extend(new_entries)
                changes_made = True
            
            # STEP 5: Save YAML
            if changes_made:
                with open(yaml_path, "w") as f:
                    yaml.dump(existing_entries, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
                
                with open("/tmp/changes_made", "w") as f:
                    f.write("yes")
                
                # Post summary
                summary_parts = []
                if additions:
                    summary_parts.append(f"✅ Added {len(additions)} photo(s)")
                if deletions:
                    summary_parts.append(f"🗑️ Removed {len(deletions)} photo(s)")
                
                summary = " | ".join(summary_parts) if summary_parts else "No changes"
                
                try:
                    client.chat_postMessage(
                        channel=channel_id,
                        text=f"🤖 Gallery updated: {summary}"
                    )
                except SlackApiError:
                    pass
                
        except SlackApiError as e:
            print(f"❌ Slack API Error: {e.response['error']}")
            exit(1)
        except Exception as e:
            print(f"❌ Error: {str(e)}")
            import traceback
            traceback.print_exc()
            exit(1)
        
        EOF
    
    - name: Commit and push if changes
      run: |
        if [ -f /tmp/changes_made ]; then
          git config user.name "Gallery Bot"
          git config user.email "bot@quantchemdev.github.io"
          git add assets/gallery/ _data/gallery/items.yml
          git commit -m "🖼️ Update gallery (added/removed images from Slack)"
          git push
          echo "✅ Changes committed and pushed"
        else
          echo "ℹ️ No changes to commit"
        fi
